version: "3"
services:
  nodejs-server:
    build:
      context: ./
    ports:
      - "3003:80"
    container_name: snake
    restart: always
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.2/16
